title: Implementation guide for the Standard for Public Code
version: 0.7.1

plugins:
  - jekyll-redirect-from

remote_theme: standard-for-public-code/jekyll-theme
include:
  - "README.md"
  - "LICENSE.md"
  - "CODE_OF_CONDUCT.md"

# baseurl: /community-implementation-guide-standard

toc: true

defaults:
  -
    scope:
      # ignore criteria/index.html, but match all other criteria pages
      # (match all criteria pages not starting with an 'i')
      path: '/criteria/[!i]*'
    values:
      breadcrumbs:
        - name: 'Criteria'
          path: '/criteria/'
      show_prev_next: true
      toc: false

  -
    scope:
      path: '/'
    values:
      breadcrumbs: true
